name: Deploy app

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile -t mywebserver:v1
#    - name: Run Docker webserver
#      run: docker run –d –p 80:80
