name: Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --t=”mywebserver”
      run: docker run –d –p 80:80 mywebserver
