name: Deploy app

on:
  push:
    branches: [ test ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile -t mywebserver:v2
  
  send-a-message:
    
    if: ${{ failure() }}
    needs: buld
    runs-on: self-hosted
    
    steps:
    - name: Send message
      run: echo "The build failed"
      
  run:
    if: ${{ success () }}
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Run Docker container
      run: docker run -d -p 81:80 mywebserver:v2
