name: Deploy app

#on:
#  push:
#    branches: [ test ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile -t mywebserver:v4 --no-cache
  
  send-a-message:
    
    if: ${{ failure() }}
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Send message
      run: echo "The build failed"
      
  run:
    if: ${{ success () }}
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: Run Docker container
      run: docker run -d -p 80:80 mywebserver:v4
      
  pull-request:
    if: ${{ success () }}
    needs: run
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Create Pull Request
      uses: alexandrublg/github_actions@test
      with:
        commit-message: update main
        title: Update main branch
        body: Update main branch
        branch: main
      
  merge-branch:
    if: ${{ success () }}
    needs: pull-request
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main

      - name: Merge staging -> main
        uses: alexandrublg/github_actions@main
        with:
          type: now
          from_branch: staging
          target_branch: main
