name: Deploy app

on:
  push:
    branches: [ test ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile -t mywebserver:v1
    
    - name: Run Docker container
      run: docker run -d -p 81:80 mywebserver:v1
